AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront Distribution for AWS Inventory Dashboard Frontend

Parameters:
  S3BucketName:
    Type: String
    Description: S3 bucket name for frontend assets
    Default: aws-inventory-dashboard-frontend
  
  CustomDomain:
    Type: String
    Description: Custom domain name (optional, leave empty if not using)
    Default: ""
  
  CertificateArn:
    Type: String
    Description: ACM Certificate ARN for custom domain (required if CustomDomain is set)
    Default: ""

Resources:
  # CloudFront Origin Access Control (for private S3 bucket)
  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: InventoryDashboardOAC
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: AWS Inventory Dashboard Frontend
        DefaultRootObject: index.html
        
        # Origins
        Origins:
          - Id: S3Origin
            DomainName: !Sub ${S3BucketName}.s3.${AWS::Region}.amazonaws.com
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !Ref CloudFrontOAC
        
        # Default Cache Behavior
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          MinTTL: 0
          DefaultTTL: 86400
          MaxTTL: 31536000
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6  # CachingOptimized
        
        # Custom Error Responses (for SPA routing)
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
        
        # Aliases (custom domain)
        Aliases: !If
          - HasCustomDomain
          - [!Ref CustomDomain]
          - !Ref AWS::NoValue
        
        # SSL Certificate
        ViewerCertificate: !If
          - HasCustomDomain
          - AcmCertificateArn: !Ref CertificateArn
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          - CloudFrontDefaultCertificate: true
        
        # Price Class
        PriceClass: PriceClass_All
        
        # Logging (optional)
        Logging:
          Bucket: !Sub ${S3BucketName}-logs
          IncludeCookies: false
          Prefix: cloudfront-logs/

Conditions:
  HasCustomDomain: !Not [!Equals [!Ref CustomDomain, ""]]

Outputs:
  DistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub ${AWS::StackName}-DistributionId
  
  DistributionDomainName:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub ${AWS::StackName}-DistributionDomainName
  
  DistributionUrl:
    Description: CloudFront Distribution URL
    Value: !Sub https://${CloudFrontDistribution.DomainName}
    Export:
      Name: !Sub ${AWS::StackName}-DistributionUrl

